# 应用名称
spring:
  application:
    name: springboot-03-mybatis
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: defaultDataSource
# 数据库连接地址
    url: jdbc:mysql://localhost:3306/myblogsystem?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
# 数据库用户名&密码：
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
# 应用服务 WEB 访问端口
server:
  port: 8080

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.gdsdxy.mybatis.entity
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

